/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as certificateSol from "./Certificate.sol";
export type { certificateSol };
export type { MatchVoting } from "./MatchVoting";
