/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SampleContract } from "./SampleContract";
export * as factories from "./factories";
export { SampleContract__factory } from "./factories/SampleContract__factory";
