/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as certificateSol from "./Certificate.sol";
export { MatchVoting__factory } from "./MatchVoting__factory";
