/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as openzeppelin from "./@openzeppelin";
export type { openzeppelin };
import type * as contracts from "./contracts";
export type { contracts };
export * as factories from "./factories";
export type { Ownable } from "./@openzeppelin/contracts/access/Ownable";
export { Ownable__factory } from "./factories/@openzeppelin/contracts/access/Ownable__factory";
export type { Certificate } from "./contracts/Certificate.sol/Certificate";
export { Certificate__factory } from "./factories/contracts/Certificate.sol/Certificate__factory";
export type { ICertificate } from "./contracts/Certificate.sol/ICertificate";
export { ICertificate__factory } from "./factories/contracts/Certificate.sol/ICertificate__factory";
export type { MatchVoting } from "./contracts/MatchVoting";
export { MatchVoting__factory } from "./factories/contracts/MatchVoting__factory";
