/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ICertificate,
  ICertificateInterface,
} from "../../../contracts/Certificate.sol/ICertificate";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "matchInput",
        type: "string",
      },
      {
        internalType: "string",
        name: "matchResult",
        type: "string",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ICertificate__factory {
  static readonly abi = _abi;
  static createInterface(): ICertificateInterface {
    return new utils.Interface(_abi) as ICertificateInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICertificate {
    return new Contract(address, _abi, signerOrProvider) as ICertificate;
  }
}
