/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Certificate__factory } from "./Certificate__factory";
export { ICertificate__factory } from "./ICertificate__factory";
